host: ""
port: 8317

tls:
  enable: false
  cert: ""
  key: ""

remote-management:
  allow-remote: true
  secret-key: ""
  disable-control-panel: false
  disable-auto-update-panel: true

auth-dir: "~/.cli-proxy-api"
api-keys: []
debug: false
request-log: false
logging-to-file: false
usage-statistics-enabled: false
ws-auth: true

plugins:
  enabled: false
  dir: "plugins"
  configs: {}
